### ISSUE TITLE
Should we create folders with symlinks to themed repositories?

### ISSUE THREAD

**Issue by sauloal** [BioDocker/biodocker#31]
Should we create folders for specific fields (proteomics, genomics, metabolomics, etc) containing symlinks to the related tools to facilitate search?

Positives: 
- Easier to find tools 
- Easier to find related tools

Negatives:
- One more thing to maintain
- There's such a thing as Ctrl+F

/cc @BioDocker/contributors

**Comment by Leprevost** [comment]
Im not sure about this, I dont want to increase the amount of "complexity"
here. In my opinion, this is OK as it is because this is a place for
developers, not users. A normal user would (or should) use the docker
search feature to look for tools, or the website for the catalog. For us it
does not matter where the software came from or where it is used for.

**Comment by sauloal** [comment]
fine by me
+1

**Comment by bgruening** [comment]
I also think this just increases complexity. Github offers a really nice search as you type feature that is enough for most cases. At some point we probably need a fancy webpage with a container search that should handle this for a user.
