### ISSUE TITLE
Official chanel for communication

### ISSUE THREAD

**Issue by Leprevost** [BioDocker/biodocker#35]
We need to establish an official communication channel, here are the options (good and bad ones):
 
* IRC channel
* E-mail group list
* Skype group
* hangouts group
* Gitter
* Whatsapp
* Telegram

Please @BioDocker/contributors, give me your feedback on this.

**Comment by sauloal** [comment]
1. Gitter
2. Hangouts
3. Telegram
4. Whatsup

**Comment by Leprevost** [comment]
+1 Gitter

**Comment by bgruening** [comment]
+1 IRC
+1 regular hangouts

**Comment by jvhaarst** [comment]
+1 Gitter/Hipchat/Slack
+1 email




On Wed, Sep 23, 2015 at 7:31 PM, Björn Grüning <notifications@github.com>
wrote:

> +1 IRC
> +1 regular hangouts
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BioDocker/biodocker/issues/35#issuecomment-142673307>.
>



-- 
Dag,
Jan

**Comment by ypriverol** [comment]
+1 Gitter
+1 Gitter
+1 regular hangouts

**Comment by lgatto** [comment]
+1 Gitter
+1 IRC

**Comment by hroest** [comment]
+1 Gitter
+1 Email list

**Comment by rajido** [comment]
I guess it depends on the purpose of the communication ...

* For TCs I would prefer hangouts.
* For questions like this as well as feature requests, ideas, bug reports, … I would keep using the github issue taking system. With this channel mailing lists are not really necessary.
* I like gitter and for support, notifications as well as hackathons/workshops might be OK (ie. https://gitter.im/biojs/biojs), however I would prefer questions and discussions to happen in the issue tracking system (structured) instead of gitter (caos). For notifications I would prefer to use Twitter.
* Twitter again. I guess if we want the world know about biodocker we need to be more active on twitter.

So …

+1 GitHub Issue tracking 
+1 Hangouts 
+1 Twitter
-1 Mailing list 
-1 Gitter

**Comment by Leprevost** [comment]
After checking all opinions and discussing this more closely at the Hangout meeting I think we can use: 

Gitter for ordinary chat (Gitter integrates with e-mail and mobile and desktop).
Github issues for official discurrion, proposals, ideas and modifications.
Hangouts for meetings.
