### ISSUE TITLE
OpenMS 2.0

### ISSUE THREAD

**Issue by prvst** [BioDocker/biodocker#43]
This is to mark the request for the OpenMS 2.0, for the Galaxy project

**Comment by Leprevost** [comment]
@bgruening , I just finished the prototype of the container, everything seems to be working, I just need to polish a little better the Dockerfile. I think I can upload the final version in the next days.

**Comment by bgruening** [comment]
Awesome! Thanks! I will work on the Galaxy side than.

**Comment by Leprevost** [comment]
The image is ready and I just updated DockerHub. The automatic build is taking some time to build everything so you should see the image ready in a couple of hours. The image by itself also takes some time due to the large number of binaries to compile and test.

There is only one problem with this image, it's size is ~ 3 GB, other than that, everything works fine, all the programs are on the container's PATH.

have fun =)

**Comment by Leprevost** [comment]
OK here is the problem: The DockerHub engine is failing for the OpenMS 2.0. It returns a 'Timeout' error, that means the build takes too much time or resources (I suspect time). To solve this I have two options, break this into separated builds (not sure yet how to do it in this specific case) or compile everything locally in my server and push the binaries into the container ( I like this one).
Any comments?

**Comment by Leprevost** [comment]
@bgruening , @ypriverol ;

The build system from OpenMS takes too long, even breaking the image in different parts takes a lot of time and the DockerHub engine times out.
The image and the container we have is working, so I guess @bgruening you can take the Dockerfile on the container repository and build it yourself locally.

**Comment by ypriverol** [comment]
@timosachsenberg @prvst @bgruening Is this problem solve?. What can we do for this long building process?

**Comment by bgruening** [comment]
@ypriverol I can ask to increase the travis max build-time and we push it? In the meantime we can build a mulled OpenMS package if this os ok for everyone?

**Comment by bgruening** [comment]
One other possibility would be to use the precompiled binaries from: https://github.com/galaxyproject/starforge and just copy them into the container.

**Comment by timosachsenberg** [comment]
Hi @jpfeuffer
maybe you can comment on that. I think you had some ideas.

**Comment by jpfeuffer** [comment]
Hey everybody.
We are currently in the process of setting up a continuous integration platform with Jenkins. Since our nightly linux builds are run on Docker containers anyway, I had the idea (after some cleanup steps of the container) to just push these built containers to DockerHub. We currently build on Ubuntu14.10 and CentOS7 but I can switch to the BioDocker base image.
What do you think?

**Comment by ypriverol** [comment]
@jpfeuffer Great Idea. Can you release in docker hub under biodckr which is the root of Biodocker. Do we need to give permissions for that @sauloal ?

**Comment by sauloal** [comment]
@jpfeuffer  @ypriverol  i'm not sure how the user management works on dockerhub, we can test
@jpfeuffer , can we chat on https://gitter.im/BioDocker/biodocker ?

**Comment by prvst** [comment]
@ypriverol  OpenMS 2.0 build OK, and it works. The problem is that DockerHub is offering less resources for building images, that means large builds, like OpenMS 2.0, will fail with an 'Timeout' errror

**Comment by prvst** [comment]
until there is no extra resources from DockerHub we can't provide this via registry, only the Dockerfile. Will maintain this closed until more is provided.

**Comment by jpfeuffer** [comment]
Ok. I will chat with @sauloal about the credentials so that we can push our own builds and as soon as we figured something out, we will report it here.
